#!/usr/bin/env python3
import os
from pathlib import Path
import yaml

def count_solved_problems():
    categories = {
        "Select": 0,
        "Basic-Joins": 0,
        "Basic-Aggregate-Functions": 0,
        "Sorting-and-Grouping": 0,
        "Advanced-Select-and-Joins": 0,
        "Subqueries": 0,
        "Advanced-String-Functions-Regex-Clause": 0
    }
    
    solved_counts = {cat: 0 for cat in categories}
    total_solved = 0
    
    base_path = Path(".")
    
    for category in categories:
        category_path = base_path / category
        if not category_path.exists():
            continue
            
        problem_folders = [f for f in category_path.iterdir() if f.is_dir()]
        categories[category] = len(problem_folders)
        
        for problem_folder in problem_folders:
            yml_file = problem_folder / "problem.yml"
            if yml_file.exists():
                try:
                    with open(yml_file, 'r', encoding='utf-8') as f:
                        data = yaml.safe_load(f)
                        if data and data.get('solved', False):
                            solved_counts[category] += 1
                            total_solved += 1
                except:
                    pass
    
    return categories, solved_counts, total_solved


def update_progress_file():
    categories, solved_counts, total_solved = count_solved_problems()
    total_problems = sum(categories.values())
    
    progress_percentage = (total_solved / total_problems * 100) if total_problems > 0 else 0
    
    content = "# 📈 Progress Tracker

"
    content += "## Overall Progress

"
    content += f"**Solved:** {total_solved} / {total_problems} ({progress_percentage:.1f}%)

"
    content += "---

"
    content += "## By Category

"
    content += "| Category | Solved | Total | Progress |
"
    content += "|----------|--------|-------|----------|
"
    
    for category, total in categories.items():
        solved = solved_counts[category]
        percentage = (solved / total * 100) if total > 0 else 0
        display_name = category.replace('-', ' ')
        content += f"| {display_name} | {solved} | {total} | {percentage:.0f}% |
"
    
    content += "
---

"
    content += "*Last updated: Auto-generated by update_progress.py*
"
    
    with open("PROGRESS.md", "w", encoding='utf-8') as f:
        f.write(content)
    
    print(f"✅ Progress updated: {total_solved}/{total_problems} problems solved ({progress_percentage:.1f}%)")


if __name__ == "__main__":
    update_progress_file()
